### ISSUE TITLE
Get ddd file directly from ShieldHit

### ISSUE THREAD

**Issue by pititomy** [DataMedSci/pymchelper#111]
Hey !

In order to facilitate the process of using ShieldHit with TriP, it would be interesting to get the ddd files directly from ShieldHit, using for example a ddd scorer.

Best regards,
Thomas

**Comment by grzanka** [comment]
Hi @pititomy ,

It would be much easier to implement converter of bdo files to ddd in pymchelper (see https://github.com/DataMedSci/pymchelper/issues/107) than implementing it directly in SHIELD-HIT12A.

The idea would be that set of .bdo files is generated with SHIELD-HIT12A and then you could use a command, like:

convertmc --converter trip98ddd path_to_bdo_files/*.bdo path_to_ddd_output_file.ddd

What do you think about that ?

It has the advantage that pymchelper can read both Fluka and SHIELDHIT12A files, so DDD could be then generated with both MC codes.

I am working now on this issue and hope to get it ready this week.

Cheers,
Leszek

**Comment by nbassler** [comment]
@grzanka propose also to make DDD scorer in SH12A for automatic setup of scorers. Placeholder is already in the SH12A code. BDO files will be DDD tagged, so pymchelper knows this BDO file is in special DDD format.

(same goes for SPC then, would resolve a lot of issues in SH12A)

**Comment by grzanka** [comment]
@nbassler OK, so this task will be postponed until SH12A issue is fixed.

**Comment by pititomy** [comment]
@grzanka Sounds good !

**Comment by nbassler** [comment]
It should be optional whether user wants to have 0,1 or 2 Gaussian fits. TRiP can handle either of these.

https://gitlab.au.dk/shieldhit/shieldhit/issues/74

**Comment by grzanka** [comment]
Can be an additional option to "trip" converter. 
There will be more options user will have to provide: projectile, material, energy, density. These options are not saved in .bdo file now.

**Comment by nbassler** [comment]
regarding double Gaussian fitting:
Journal of Radiation Research, 2013, 54, i91–i96 doi: http://doi.org/10.1093/jrr/rrt051
from @TokePrintz
