### ISSUE TITLE
Image converter doesn't produce images with correct units when used with -n option

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/pymchelper#126]
I.e. `convertmc --many "*.bdo" plots/. --converter image  -n 871250000000` gives correct results but with MeV/g/prmary not in Gy

it should be also possible to provide particle number as float

**Comment by nbassler** [comment]
to be precise, what is plotted is [MeV/g], and the legend is set to [MeV/g/primary]. 

What should be plotted is [Gy].
