### ISSUE TITLE
Abandoning compatibility with old bdo2txt

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/pymchelper#129]
Questions:
 - default converter writes number in Fortran formatting (0.100D+06, 0.0000000E+00), while python is using different formatting. Fluka is also using Fortran formatting. Should it be kept  ?
Pros: easier comparison of text output with Fluka (making plain text diff)
Cons: for users it probably doesn't matter, fortran formatting is time consuming when converting large files, extra code can be removed from repo.

- default converter keeps header in same way as bdo2txt. Removing compatibility allows us to redesign header field.

- we have now two converters producing ASCII files: default and plotdata. They can be merge into one and decision on the number of columns moved to a switch. Lets take 1-D scoring (i.e. dose profile) which gives us 1 variable axis (column) and 1 column of data. Two columns are fixed. We could have following behaviour:
  - `convertmc dose.bdo` will produce plain ASCII file with 5 columns (X,Y,Z, data, errors)
  - `convertmc dose.bdo --plotdata` will produce file with 3 columns(Z,data, errors) automatically figuring out which column is variable. X and Y position can be saved to header.
for gnuplot it would work this way:
  - `convertmc dose.bdo --converter default, gnuplot` will file with 5 columns and gnuplot script reading from a such file.
  - `convertmc dose.bdo --converter default, gnuplot --plotdata` will produce file with 3 columns and gnuplot script reading from 3-columns file.

**Comment by nbassler** [comment]
Make an option --style=fortran or --style=fluka and lets get rid of bdo2txt once an for all.

I dont mind several ASCII generators. I am very happy with the default one, I have never used the gnuplot one, as I would assume this is specific to gnuplot, which I never use.

**Comment by nbassler** [comment]
bdo2txt will be removed in SH12A as 0.5.0

**Comment by nbassler** [comment]
@grzanka SH12A 0.5.0 has just been released. Not sure this issue is relevant anymore?

**Comment by nbassler** [comment]
cloooooooose meeeeeee.....

**Comment by nbassler** [comment]
Closed, since a new .bdo format was created.
