### ISSUE TITLE
Trouble with convertmc

### ISSUE THREAD

**Issue by NatMoj** [DataMedSci/pymchelper#133]
While following these steps:
1. source $PLG_GROUPS_STORAGE/plggccbmc/software/setup.sh
2. convertmc --many "output/*" --converter plotdata
I got an error:
**/net/software/local/python/3.4.2/bin/python3.4: error while loading shared libraries: libpython3.4m.so.1.0: cannot open shared object file: No such file or directory**
Then when I tried: 
**module load/python/3.4.2**
I did not receive an error, but .dat files were not generated.

**Comment by grzanka** [comment]
Please paste here contents of your `.bashrc` and `.bash_profile`. 

PS. I recommend to use Markdown formatting to nicely print the code, see https://guides.github.com/features/mastering-markdown/

**Comment by grzanka** [comment]
Fixed in private communication
