### ISSUE TITLE
Units in DDD files

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/pymchelper#138]
DDD files found in TRiP98 package have header with [g/cm**2] units of FWHM.

Currently we are saving DDD files with data in [cm] (or [g/cm**2] as only water is supported) units, with (wrong) header which says:
```#   z[g/cm**2] dE/dz[MeV/(g/cm**2)] FWHM1[mm] factor FWHM2[mm]```

Header should be consisent with data units.

In the file `ddd.py` from SH12A source there was a line related to units change, from [cm] to [mm].
See https://github.com/DataMedSci/pymchelper/pull/116/commits/c5bc9f1edff195f96c3b4fc72c394886f15b2951#diff-11b22823f3d8993745a6d6d0e130d049R318 

```
# Scale from cm to mm according to Gheorghe from Marburg
FWHM1 *= 10.0
FWHM2 *= 10.0
```

We should figure out which units TRiP98 is using and use them consistently.

**Comment by grzanka** [comment]
See also http://bio.gsi.de/DOCS/TRiP98/CLASSIC/DOCS/trip98fmtddd.html

```
Depth dose distribution file format

!filetype    ddd
!fileversion <yyyymmdd>
!filedate    <dow> <mmm> <dd> <hh>:<mm>:<ss> <yyyy>
# 
# Comment
#
!projectile    <element-symbol>
!material      <material name>
!composition   <material composition>
!density       <material density / g/cm**3 > 
!energy        <beam energy / MeV/u >
#   z[g/cm**2] dE/dz[MeV/(g/cm**2)] FWHM1[g/cm**2] factor FWHM2[g/cm**2]
!ddd
<depth> <ionization> [ <FWHM1> <factor> <FWHM2> ] 
```

**Comment by TokePrintz** [comment]
Hello all,

The units for FWHM1 and FWHM2 should be [g/cm**2]. The [mm] unit was an old mistake I did in my first update of ddd.py in the early 2015, but I later realized the error and I could have sworn that I changed it and recommitted! 

Sorry for the confusion.
