### ISSUE TITLE
Error bar calculations, double check

### ISSUE THREAD

**Issue by nbassler** [DataMedSci/pymchelper#162]
Comments look strange.

in detector.py line 112
```
        if error_estimate != ErrorEstimate.none:
            self.error = np.nanstd(l, axis=0, ddof=1)  # stddev = sqrt( var / (n-1) )
```
comment a bit confusing. stddev = sqrt(1/(n-1)sum(x-x_mean)² = s where 

- s² is the "unbiased sample variance"
- s is the "corrected sample standard deviation"
- S = s/sqrt(N) is the "corrected standard deviation of the mean" (i.e. "standard error")
and then in line 317:

```
    #   stderr = stddev / sqrt(n)
    if len(input_file_list) > 1 and options.error == ErrorEstimate.stderr:
        first.error /= np.float64(first.counter)
```
```sqrt()``` missing?

**Comment by grzanka** [comment]
Yes, you are right, sqrt seems to be missing. I'll also improve comments
