### ISSUE TITLE
convertmc error

### ISSUE THREAD

**Issue by NatMoj** [DataMedSci/pymchelper#169]
After:
`convertmc txt --many "output/*" ./txt_output/`
the error occures:
net/software/local/python/3.4.2/bin/python3.4: error while loading shared libraries: libpython3.4m.so.1.0: cannot open shared object file: No such file or directory

**Comment by grzanka** [comment]
Read cluster manual first, before issuing that command you should type sth like `source ....`

**Comment by NatMoj** [comment]
My mistake. I forgot to load:
`source $PLG_GROUPS_SHARED/plggccbmc/software/setup.sh`
