### ISSUE TITLE
convertmc txt

### ISSUE THREAD

**Issue by NatMoj** [DataMedSci/pymchelper#172]
After typing:
`convertmc txt --many "output*/" ./txt_output`
no .txt file is been generated and no errors occured.

**Comment by grzanka** [comment]
It is correct as the expression you provided as input path: `"output*/"` cannot select any input files.
Do you see a difference between `"output*/"` and `"output/*"` ?

**Comment by NatMoj** [comment]
Thank you! I was quite sure that I did something wrong, but I could not find what it is.
