### ISSUE TITLE
convertmc tripcube produces negative slice distances

### ISSUE THREAD

**Issue by nbassler** [DataMedSci/pymchelper#174]
1. slice distance seems to be filled with a bogus value
2. also "Anonymous" is spelled wrong.
3. add pymchelper and PyTRiP version number to creation info, and check spelling "created"
4. use proper case of PyTRiP98
5. pixel size is a factor 10 wrong
```
$ convertmc -V
0.6.1
$ convertmc tripcube myvox02.bdo
$ cat myvox02.hed 
version 2.0
modality CT
created_by pytrip
creation_info create by pytrip
primary_view transversal
data_type integer
num_bytes 2
byte_order vms
patient_name Anonymeous
slice_dimension 102
pixel_size 0.121093802154
slice_distance -0.303921699524
slice_number 102
xoffset 0
dimx 256
yoffset 0
dimy 256
zoffset 0
dimz 102
z_table no
```

**Comment by grzanka** [comment]
Can you upload here input bdo file ? Or provide a location where to find it (i.e. Krakow cluster) .

**Comment by nbassler** [comment]
it is the default BDO files created from test/26 in SH12A

**Comment by nbassler** [comment]
@grzanka we must agree what units the local detector values are in.
I think detector.xmax and similar should be in [cm] just as they are in FLUKA and SH12A, right?

**Comment by nbassler** [comment]
Looks like the bad distances is due to a problem in SH12A saving the values.

**Comment by grzanka** [comment]
I agree - cm is more natural units.

**Comment by nbassler** [comment]
Ok, cm it is.

The bad distance wasn't a problem in SH12A after all, but wrong index alignment in trip98.py
