### ISSUE TITLE
default options are not shown with --help

### ISSUE THREAD

**Issue by nbassler** [DataMedSci/pymchelper#175]
```
bassler@baslup:~/Projects/pymchelper$ PYTHONPATH=. python3 pymchelper/run.py  --help
usage: run.py [-h] [-V] converter ...

positional arguments:
  converter
    txt          converts to plain txt file
    image        converts to PNG images
    plotdata     converts to gnuplot data
    gnuplot      converts to gnuplot script
    tripcube     converts to trip98 data cube
    tripddd      converts to trip98 ddd file

optional arguments:
  -h, --help     show this help message and exit
  -V, --version  show program's version number and exit
```

where are --many --verbose  input and output?

**Comment by grzanka** [comment]
These options (`--many` and `--verbose`) belong to converter, not to main application.
In other words user cannot type `convertmc --many "*.bdo" image` or `convertmc --verbose image 1.bdo 1.png`, but has to type  `convertmc image --many "*.bdo"` or `convertmc image --verbose 1.bdo 1.png`

Options proceeding converter name are not shown in main help message. They appear when you type:
`convertnc image --help`.

This is default behaviour of option parser. We can bypass it by manually crafting help message, but this would become hard to maintain.

I think this problem might be solved by adding a line in help message saying i.e.:
`type convertmc <converter> --help` to see a help for specifing...

 See for example:

```
→ svn --help
usage: svn <subcommand> [options] [args]
Subversion command-line client, version 1.8.8.
Type 'svn help <subcommand>' for help on a specific subcommand.
Type 'svn --version' to see the program version and RA modules
  or 'svn --version --quiet' to see just the version number.

Most subcommands take file and/or directory arguments, recursing
on the directories.  If no arguments are supplied to such a
command, it recurses on the current directory (inclusive) by default.

Available subcommands:
   add
   blame (praise, annotate, ann)
   cat
```

**Comment by nbassler** [comment]
yes, agreed, that would be more obvious if this is stated in the helptext.

**Comment by grzanka** [comment]
Maybe some of these could be useful: https://docs.python.org/3/library/argparse.html#argumentparser-objects
