### ISSUE TITLE
No header in txt from mcgenerate and convertmc workflow OR newest bdo2txt 

### ISSUE THREAD

**Issue by TokePrintz** [DataMedSci/pymchelper#199]
So, learning to use the plgrid cluster and the new tools (mcgenerate, pymchelper) I did a run of depth-dose distributions for different energies. The runs were started with a bash script and the mcgenerate command. The output is .bdo files. The collect.sh script and the convertmc command was afterwards used to collect and convert the data. 
However, the txt files are all only raw numbers without any header containing bin numbers and such information, which I have grown accustomed to. 

I also checked the output of bdo2txt on the .bdo files, which also did not contain any header. I then checked the output of bdo2txt on old .bdo files, which before resulted in txt files with headers - this time they did not. So maybe the issue is also in the latest version of bdo2txt (--version returns X.Y.Z but it was compiled at the end of 2016).

For my post-processing scripts, I very often draw information from the headers. I am aware of the option to import and work with the binaries with pymchelper without converting and I will also start playing with that. Independently however, a header also in the txt files would be nice. They can also be helpful to remember what was done.   
If bdo2txt is slowly being phased out, then I guess it would make sense only to add the feature in convertmc.

Here is an example of a header from a txt file converted from .bdo with a bdo2txt version from 1-2 years ago:

```
#   DETECTOR OUTPUT
#   R BIN:     1 PHI BIN:     1 Z BIN:  1000
#   JPART:    -1 DETECTOR TYPE:DOSE      
#   R START: 0.000D+00 PHI START: 0.000D+00 Z START: 0.000D+00
#   R END  : 0.100D+02 PHI END  : 0.628D+01 Z END  : 0.500D+02
#   PRIMARIES: 0.500D+06
 0.5000000E+01  0.3141593E+01  0.2500000E-01  0.6139658107392230E-01
...
...
(und so weider)
```

**Comment by grzanka** [comment]
Could you please write here exact `convertmc` command which you've used (including switches) and fragment of detect.dat file which describes the scorer being used ?

**Comment by TokePrintz** [comment]
```
[prometheus][plgtpr@login01 run_20170308_083136]$ convertmc txt output/50CrD10001.bdo 
INFO:pymchelper.readers.shieldhit:Reading header: output/50CrD10001.bdo
INFO:pymchelper.readers.shieldhit:Reading data: output/50CrD10001.bdo
INFO:pymchelper.writers.shieldhit:Writing: output/50CrD10001.txt
```
(so it writes it is reading header from .bdo but does not return a header in the txt)

Concerning the sorer of detect.dat: Not sure I understand. Shouldn't a header be written independently of choice of scoring information?
But here is the detect.dat file:
```
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7..
CYL              0.0       0.0       0.0      10.0       7.0      40.0
                 400         1      1000        -1      DOSE    XXXCrD
* ..+....1....+....2....+....3....+....4....+....5....+....6....+....7..
CYL              0.0       0.0       0.0      10.0       7.0      40.0
                   1         1      1000        -1      DOSE   XXXCrD1
```

**Comment by grzanka** [comment]
Well, here is the problem:
https://github.com/DataMedSci/pymchelper/blob/master/pymchelper/writers/shieldhit.py#L121

```
        # due to some bug in original bdo2txt converter, no header is generated for cylindrical mesh
        if det.geotyp in (SHGeoType.cyl, SHGeoType.dcyl, ):
            header = ""
```

**Comment by grzanka** [comment]
Let us see if PR #200 would solve the problem

**Comment by grzanka** [comment]
There is still some issue when comparing files generated with bdo2txt and convertmc, see:
https://travis-ci.org/DataMedSci/pymchelper/jobs/208932988

I will investigate it further.

**Comment by grzanka** [comment]
@TokePrintz ok, I've figured it out. Original bdo2txt is also not saving header for cylindrical scoring of: fluence, energy, beta and avg energy - can you confirm this ?

I've modified the code of convertmc to do the same.

This means that headers will be generated for cylindrical scoring of dose, but not for abovementioned values.

**Comment by TokePrintz** [comment]
@grzanka Depends on what is meant with "original bdo2txt". The latest one does indeed not give a header (see the opening comment of this thread). But I found the binaries of a r676-version of SHIELD-HIT (smth like 2 years old) on my computer and the bdo2xt command for that distribution does return a header. So at some point it worked and then at some later point it stopped working.

**Comment by grzanka** [comment]
Can you check if your r676 bdo2txt generate headers for cylindrical scoring of fluence (not of the dose) ?

**Comment by TokePrintz** [comment]
It doesn't. Only for DOSE.
But the current version of bdo2txt return no header for neither scored DOSE nor FLUENCE.

**Comment by grzanka** [comment]
OK, thanks !

Nevertheless we have plans to abandon compatibility with bdo2txt and write header for all cases. This would also mean that new header format will be introduced.
Old bdo2txt-style format will be kept as deprecated and optional and not maintained.
