### ISSUE TITLE
Implement support for single differential binning

### ISSUE THREAD

**Issue by nbassler** [DataMedSci/pymchelper#205]
for SH12A this may be either
- energy
- LET
- angle

Data are properly exported in new BDO fileformat.

**Comment by grzanka** [comment]
A bit was added here:
https://github.com/DataMedSci/pymchelper/commit/a69d37baa9b5050961a4df655dc4649ee7688d88

checkout PR #190 and issue #189

**Comment by nbassler** [comment]
This is the part which causes trouble. Apparently it produces different output whether it is a new or old BDO type of file.

**Comment by grzanka** [comment]
I can investigate it (next week :( ). Removing this part will break support for DPLANE.

I think the reason that it is producing different output might be simple - such functionality is not implemented for old BDO type of files.

Adding similat trick for old format would solve the problem. I know its dirty hack, but it allows to produce plots for differential scorers.

**Comment by nbassler** [comment]
In that case, I propose simply to establish a new reference file in the SH12A test, and leave this for now. It is not that urgent to have it fixed in pymchelper. It is more needed to get the new SH12A release out.

**Comment by grzanka** [comment]
Sure, new reference file is OK

**Comment by nbassler** [comment]
closed via PR #260
