### ISSUE TITLE
Convertmc tripddd error

### ISSUE THREAD

**Issue by pititomy** [DataMedSci/pymchelper#206]
Error following the command:
convertmc tripddd ddd_130.bdo ddd_130.ddd

Error:
INFO:pymchelper.readers.shieldhit:Reading: ddd_130.bdo
Traceback (most recent call last):
  File "/usr/local/bin/convertmc", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pymchelper/run.py", line 118, in main
    merge_list(files, parsed_args.output, parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/pymchelper/detector.py", line 330, in merge_list
    first.save(output_file, options)
  File "/usr/local/lib/python2.7/dist-packages/pymchelper/detector.py", line 149, in save
    writer.write(self)
  File "/usr/local/lib/python2.7/dist-packages/pymchelper/writers/trip98.py", line 131, in write
    self._extract_data(detector)
  File "/usr/local/lib/python2.7/dist-packages/pymchelper/writers/trip98.py", line 261, in _extract_data
    r_step_cm = self.r_data_cm_1d[1] - self.r_data_cm_1d[0]
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by grzanka** [comment]
Can you provede more details, by running:

```
shieldhit -V
convertmc --version
```

?

What if you run:

```
convertmc tripddd ddd_130.bdo ddd_130.ddd -vvv
```

?

**Comment by pititomy** [comment]
shieldhit -V
 SHIELD-HIT12A Version 0.6.0
 Build date: Fri Mar 17 09:03:11 CET 2017

convertmc --version
0.6.7

convertmc tripddd ddd_130.bdo ddd_130.ddd -vvv
INFO:pymchelper.readers.shieldhit:Reading: ddd_130.bdo
DEBUG:pymchelper.readers.shieldhit:Magic : xSH12A
DEBUG:pymchelper.readers.shieldhit:Endian: II
DEBUG:pymchelper.readers.shieldhit:VerStr: 0.6
DEBUG:pymchelper.readers.shieldhit:Read token S8 0x00
DEBUG:pymchelper.readers.shieldhit:MC code version:0.6.0
DEBUG:pymchelper.readers.shieldhit:Read token S32 0x01
DEBUG:pymchelper.readers.shieldhit:Read token S32 0x02
DEBUG:pymchelper.readers.shieldhit:Read token S8 0x03
DEBUG:pymchelper.readers.shieldhit:Read token S8 0x04
DEBUG:pymchelper.readers.shieldhit:Read token <f8 0xcc00
DEBUG:pymchelper.readers.shieldhit:Read token <f8 0xcc01
DEBUG:pymchelper.readers.shieldhit:Read token <f8 0xcc04
DEBUG:pymchelper.readers.shieldhit:Read token <f8 0xcc10
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xcc02
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xcc03
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xcc05
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xcc06
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xcc07
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xcc08
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xcc09
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xcc0a
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xcc0b
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xcc0c
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xcc0d
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xcc0e
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xcc0f
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xcc0e
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xcc11
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xaa00
DEBUG:pymchelper.readers.shieldhit:Read token S16 0xee00
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xee01
DEBUG:pymchelper.readers.shieldhit:Read token S16 0xdd00
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xdd01
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xdd02
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xdd03
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xdd04
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xdd05
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xdd06
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xdd07
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xdd08
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xdd09
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xdd0a
DEBUG:pymchelper.readers.shieldhit:Read token <i8 0xdd0b
DEBUG:pymchelper.readers.shieldhit:Read token <f8 0xdd0c
DEBUG:pymchelper.readers.shieldhit:Read token <f8 0xdd0d
DEBUG:pymchelper.readers.shieldhit:Read token <f8 0xdd0e
DEBUG:pymchelper.readers.shieldhit:Read token <f8 0xdd0f
DEBUG:pymchelper.readers.shieldhit:Read token <f8 0xdd10
DEBUG:pymchelper.readers.shieldhit:Read token <f8 0xddbb
DEBUG:pymchelper.readers.shieldhit:Done reading bdo file.
DEBUG:pymchelper.readers.shieldhit:Detector data : [  3.05070679e+05   6.13094200e+05   9.20003004e+05   1.23740451e+06
   1.55606278e+06   1.86311225e+06   2.16667287e+06   2.49663353e+06
   2.84967946e+06   3.19050283e+06   3.52792830e+06   3.83231548e+06
   4.13392487e+06   4.47169947e+06   4.80633229e+06   5.14797995e+06
   5.44432301e+06   5.70759695e+06   6.06560006e+06   6.41049521e+06
   6.75299691e+06   7.07400810e+06   7.40494231e+06   7.76327834e+06
   8.07364950e+06   8.41324621e+06   8.75064308e+06   9.09891619e+06
   9.44158469e+06   9.82649884e+06   1.01529305e+07   1.04852648e+07
   1.08500314e+07   1.11813099e+07   1.14835089e+07   1.18590312e+07
   1.21896323e+07   1.25548283e+07   1.28935600e+07   1.32612209e+07
   1.36993472e+07   1.39783281e+07   1.43289550e+07   1.47465913e+07
   1.50398474e+07   1.53865766e+07   1.56646591e+07   1.59720322e+07
   1.63372847e+07   1.66824759e+07   1.69754788e+07   1.73233336e+07
   1.77514687e+07   1.80869065e+07   1.83448977e+07   1.87420995e+07
   1.90979452e+07   1.94282194e+07   1.98502758e+07   2.01530829e+07
   2.04598636e+07   2.08233616e+07   2.12411320e+07   2.17057074e+07
   2.20697371e+07   2.24093944e+07   2.26514979e+07   2.29475282e+07
   2.32825174e+07   2.36320496e+07   2.39950133e+07   2.43371895e+07
   2.47627939e+07   2.51391526e+07   2.55288043e+07   2.58245056e+07
   2.61612439e+07   2.66595669e+07   2.70322049e+07   2.74586888e+07
   2.79992415e+07   2.82832547e+07   2.87794621e+07   2.91440514e+07
   2.95370079e+07   3.00165355e+07   3.02854981e+07   3.07010149e+07
   3.11060651e+07   3.13997223e+07   3.18909976e+07   3.22075746e+07
   3.25242466e+07   3.28814336e+07   3.32493531e+07   3.37373790e+07
   3.41664742e+07   3.45805877e+07   3.49647899e+07   3.52501430e+07
   3.57077205e+07   3.63016879e+07   3.66670706e+07   3.70198920e+07
   3.75005966e+07   3.79210440e+07   3.82285079e+07   3.85707626e+07
   3.89086691e+07   3.93492182e+07   3.97411022e+07   4.02006271e+07
   4.06893448e+07   4.10415333e+07   4.16741031e+07   4.19245977e+07
   4.22558907e+07   4.25307032e+07   4.30643480e+07   4.36440836e+07
   4.39297989e+07   4.42822479e+07   4.47029422e+07   4.51413777e+07
   4.55931111e+07   4.60920034e+07   4.64266343e+07   4.67699349e+07
   4.71700590e+07   4.75438465e+07   4.80440533e+07   4.85949477e+07
   4.90917803e+07   4.92759713e+07   4.97386199e+07   5.02449286e+07
   5.05715631e+07   5.10890933e+07   5.14491476e+07   5.19208587e+07
   5.24045121e+07   5.28108470e+07   5.31572037e+07   5.34649182e+07
   5.39621349e+07   5.45371258e+07   5.51272377e+07   5.57495002e+07
   5.60857791e+07   5.63411017e+07   5.67058592e+07   5.71692692e+07
   5.77129782e+07   5.81386803e+07   5.85937655e+07   5.91859155e+07
   5.95879175e+07   6.03487002e+07   6.08462833e+07   6.10888559e+07
   6.15728345e+07   6.18521214e+07   6.22398949e+07   6.27654043e+07
   6.33705607e+07   6.39573193e+07   6.43788964e+07   6.47202578e+07
   6.52036912e+07   6.56889887e+07   6.59026887e+07   6.63763177e+07
   6.70664237e+07   6.74473915e+07   6.80643506e+07   6.84519215e+07
   6.90538175e+07   6.99019596e+07   7.05370379e+07   7.10010759e+07
   7.14689787e+07   7.19777264e+07   7.26289365e+07   7.32500656e+07
   7.38105430e+07   7.41367753e+07   7.44652971e+07   7.49896757e+07
   7.58654657e+07   7.64678656e+07   7.72048608e+07   7.77700450e+07
   7.81101487e+07   7.88065694e+07   7.91749903e+07   7.98010041e+07
   8.02648329e+07   8.09186935e+07   8.16583866e+07   8.21919115e+07
   8.27620806e+07   8.32114127e+07   8.37539404e+07   8.45181880e+07
   8.50584079e+07   8.55236320e+07   8.63053480e+07   8.68301414e+07
   8.72056801e+07   8.80012494e+07   8.86880898e+07   8.94313500e+07
   9.04624131e+07   9.11681335e+07   9.17833041e+07   9.27392654e+07
   9.35355181e+07   9.40930882e+07   9.49724210e+07   9.54105504e+07
   9.64679813e+07   9.72996457e+07   9.79403321e+07   9.89327385e+07
   9.97770079e+07   1.00711348e+08   1.01258332e+08   1.02194282e+08
   1.03063173e+08   1.04111898e+08   1.05489788e+08   1.06835706e+08
   1.07817356e+08   1.08620062e+08   1.09615386e+08   1.11212222e+08
   1.12118547e+08   1.13356711e+08   1.15173737e+08   1.16159513e+08
   1.17826886e+08   1.19788123e+08   1.20971502e+08   1.22374801e+08
   1.23415103e+08   1.24448394e+08   1.25289867e+08   1.25857002e+08
   1.26734934e+08   1.27482150e+08   1.27406778e+08   1.27616818e+08
   1.27346565e+08   1.27583837e+08   1.27628892e+08   1.27512745e+08
   1.27214195e+08   1.27449426e+08   1.27547684e+08   1.27651490e+08
   1.28037648e+08   1.27363202e+08   1.27736035e+08   1.27660004e+08
   1.27255980e+08   1.27255074e+08   1.27346414e+08   1.26926229e+08
   1.27020483e+08   1.26768760e+08   1.26925424e+08   1.27015874e+08
   1.27097544e+08   1.27251477e+08   1.27834834e+08   1.27819303e+08
   1.27534249e+08   1.27283008e+08   1.27562075e+08   1.27942284e+08
   1.27903701e+08   1.27941861e+08   1.27422198e+08   1.27712703e+08
   1.27342672e+08   1.27061031e+08   1.27158416e+08   1.26969466e+08
   1.26961060e+08   1.27479541e+08   1.27842445e+08   1.27902019e+08
   1.27595579e+08   1.27957336e+08   1.27911637e+08   1.27481172e+08
   1.27347362e+08   1.27154011e+08   1.27148707e+08   1.27504411e+08
   1.27119953e+08   1.26709792e+08   1.26320169e+08   1.26631238e+08
   1.26789261e+08   1.26343880e+08   1.26691725e+08   1.27039861e+08
   1.27285549e+08   1.26989497e+08   1.27515325e+08   1.27308030e+08
   1.27506402e+08   1.27046564e+08   1.26607364e+08   1.27139272e+08
   1.27290974e+08   1.27284118e+08   1.27606097e+08   1.27393516e+08
   1.27183275e+08   1.27021760e+08   1.27323540e+08   1.27625504e+08
   1.27525375e+08   1.27115058e+08   1.27591825e+08   1.27617197e+08
   1.26921838e+08   1.27604296e+08   1.26834006e+08   1.27153701e+08
   1.26866866e+08   1.26587268e+08   1.26678182e+08   1.26810380e+08
   1.26848607e+08   1.27043822e+08   1.26827671e+08   1.26730694e+08
   1.27029724e+08   1.27185830e+08   1.26857416e+08   1.26408933e+08
   1.26900488e+08   1.27166207e+08   1.26846709e+08   1.26918288e+08
   1.26973161e+08   1.26713978e+08   1.26607468e+08   1.26267979e+08
   1.26715599e+08   1.27086317e+08   1.26885648e+08   1.26812827e+08
   1.26958143e+08   1.26997396e+08   1.27045403e+08   1.26634132e+08
   1.26537834e+08   1.26785496e+08   1.26975952e+08   1.27172043e+08
   1.27272896e+08   1.27178781e+08   1.26761880e+08   1.27423008e+08
   1.26590764e+08   1.27178169e+08   1.27415064e+08   1.27259464e+08
   1.27392524e+08   1.27007979e+08   1.27156913e+08   1.27597849e+08
   1.27359961e+08   1.27192190e+08   1.27003846e+08   1.27184913e+08
   1.27101186e+08   1.27008441e+08   1.27181760e+08   1.27125082e+08
   1.27002840e+08   1.27182169e+08   1.27539536e+08   1.27565301e+08
   1.27119339e+08   1.27189831e+08   1.27379693e+08   1.27333280e+08
   1.27585520e+08   1.27944603e+08   1.28022012e+08   1.28214501e+08
   1.27668157e+08   1.27457392e+08   1.27111699e+08   1.27080677e+08]
DEBUG:pymchelper.readers.shieldhit:Detector nstat: 1000000
DEBUG:pymchelper.readers.shieldhit:Detector nx   : 1
DEBUG:pymchelper.readers.shieldhit:Detector ny   : 1
DEBUG:pymchelper.readers.shieldhit:Detector nz   : 400
Traceback (most recent call last):
  File "/usr/local/bin/convertmc", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pymchelper/run.py", line 118, in main
    merge_list(files, parsed_args.output, parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/pymchelper/detector.py", line 330, in merge_list
    first.save(output_file, options)
  File "/usr/local/lib/python2.7/dist-packages/pymchelper/detector.py", line 149, in save
    writer.write(self)
  File "/usr/local/lib/python2.7/dist-packages/pymchelper/writers/trip98.py", line 131, in write
    self._extract_data(detector)
  File "/usr/local/lib/python2.7/dist-packages/pymchelper/writers/trip98.py", line 261, in _extract_data
    r_step_cm = self.r_data_cm_1d[1] - self.r_data_cm_1d[0]
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by grzanka** [comment]
I see what can be an issue. Can you also paste a fragment of `detect.dat` file which was used to generate `ddd_130.bdo` ?

**Comment by pititomy** [comment]
Here it is (formatting was lost in the pasting):

CYL              0.0       0.0       0.0       2.5         7      20.0
                   1         1       400        -1       DDD   ddd_130

Did I do something wrong in the binning ?

**Comment by grzanka** [comment]
You should have more than one bin (preferably ~100 bins) along `R` axis to get the gaussian lateral profile in DDD files.

**Comment by pititomy** [comment]
Thanks!
Now I'm running into a segmentation fault error when I try to bin the R axis with more than 7 bins.
Niels said it is a SHIELD-HIT issue and will investigate it. I guess this issue can then be closed.

**Comment by grzanka** [comment]
Sure, if you have troubles with SHIELD-HIT12A you can also let me know, but not here :)
