### ISSUE TITLE
pld2sobp: adjust for energy

### ISSUE THREAD

**Issue by nbassler** [DataMedSci/pymchelper#210]
`.pld` files contain the number of MUs (== "meterset") for each spot. This is a number which is proportional to the dose in the Ionization Chamber.

In order to translate this to the amount of particles, one may have to divide with the stopping power to air for that particular energy. 

As a minimum we can extract some number proportional to the number of particles to be delivered in each spot, which is what the MC codes need.

**Comment by nbassler** [comment]
```
def air(energy):
    """
    :params energy: Proton energy in MeV
    :returns: stopping power in MeV/u

    Valid from 1 to 500 MeV.
    """
    x = log(energy)
    y = 5.4041 - 0.66877 * x - 0.034441 * x*x - 0.0010707 * x*x*x + 0.00082584 * x*x*x*x
    return exp(y)
```
![air](https://cloud.githubusercontent.com/assets/7140398/25183333/903275d4-2517-11e7-8278-fce274e43781.png)

**Comment by nbassler** [comment]
Grey line is ICRU 49.

**Comment by grzanka** [comment]
Its logarithmic scale, so hard to see how good the fit is. What if you divide one by another ?

**Comment by nbassler** [comment]
On log scale you will see *relative* errors very well, IMHO.

**Comment by nbassler** [comment]
SHIELD-HIT12A quick-calculated depth dose distributions from the given .pld files which have the same amount of MU but very different energies:

![pldtest](https://cloud.githubusercontent.com/assets/7140398/25293234/366093e6-26da-11e7-8ef4-8fb4299b816b.png)

Output scaled with -n option using the estimated number of particles provided by pld2sobp.dat
This confirms that the stopping power scaling has to be used.

@grzanka do you have any data on the absolute dose for the three pld files in the entry position? Then i can scale according before merge.

**Comment by nbassler** [comment]
Plot should be [Gy] vs [cm] for the provided .pld files.
