### ISSUE TITLE
Convertion of detection TLET and DLET with --converter plotdata

### ISSUE THREAD

**Issue by vtaasti** [DataMedSci/pymchelper#24]
I have found a problem with the bdo2txt.py converter file, when converting a bdo-file with a single region of detection and using the converter: --converter plotdata 
When the scoring is done with TLET or DLET I get 30 results in the .txt.dat file instead of just one result. For all other scorers like energy, dose and so on, even for DLETG and TLETG it works fine and only a single result gets out.
It should be mentioned that 30 is exactly the number of jobs I ran in parallel to get the bdo-files in the first place, so this may explain why there are 30 entries in the file. But the mean value does not correspond to the real value I get when I use the --converter standard

Further, for TLETG and DLETG the results with both types of converter options seem to giving a scaling factor. The results are scaled down by a factor of 10^5 which is the number of primary particles in a single job (out of the 30 parallel jobs).

Kind regards Vicki Taasti

[Converter_problem.zip](https://github.com/DataMedSci/pymchelper/files/327965/Converter_problem.zip)

**Comment by grzanka** [comment]
I confirm the bug, working on it.
