### ISSUE TITLE
Logarithmic binning for SH12A differential scorer

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/pymchelper#263]
SH12A logarithmic scoring probably supports logarithmic binning (via negative number of bins). Add this capability to the SH12A reader

**Comment by grzanka** [comment]
It may be done easily via:
```
            if ny > 0:
                binnig = MeshAxis.BinningType.linear
            else:
                binnig = MeshAxis.BinningType.logarithmic
            detector.y = MeshAxis(n=np.abs(ny), min_val=ymin, max_val=ymax,
                                  name=yname, unit=yunit, binning=binnig)
```

It seems to work nicely with `--log y` option for image plotter:
![1](https://user-images.githubusercontent.com/7374733/31783274-fae8b89a-b4fd-11e7-8144-c63795aa400e.png)

**Comment by nbassler** [comment]
Would be nice with some sub-ticks between the decades.

**Comment by grzanka** [comment]
This should be some separate issue as handling the subticks in matplotlib is a bit difficult
