### ISSUE TITLE
error when trying to create a tripddd-file

### ISSUE THREAD

**Issue by fkalholm** [DataMedSci/pymchelper#337]
Hi!
I tried to create a ddd-file for using in trip, but I got an error when trying to do so. I was a little uncertain for how to enter the arguments in the "projectile" parameter, but I got the same error for both 0 and 1. See screenshow below, and let me know if I can hep in anyway!

![image](https://user-images.githubusercontent.com/56075532/66042789-bc735c80-e51d-11e9-86d3-68ce3a68cf7d.png)

**Comment by grzanka** [comment]
Hi, which version of SHIELD-HIT12A was used to generate BDO file ? Have you been using DDD scorer in SHIELD-HIT12A ?

Nevertheless error messages should be improved

**Comment by fkalholm** [comment]
Hi Leszek,
Its version SHIELD-HIT12A Version 0.7.4+dev, and I used the old scoring method, see screenshot:
![image](https://user-images.githubusercontent.com/56075532/66047679-78d22000-e528-11e9-82eb-921ee2fe9355.png)

**Comment by grzanka** [comment]
Can you try with `DDD` instead of `ENERGY`, I also advice to start with `--ngauss` set to 0 at the beginning

**Comment by fkalholm** [comment]
Thanks Laszek, that was it!
