### ISSUE TITLE
scripting engine

### ISSUE THREAD

**Issue by nbassler** [DataMedSci/pymchelper#338]
Idea of a generic scripting engine, which will autogenerate and run many files
I thought of a more gnerelized version of https://github.com/nbassler/TRiPddd/blob/master/prepare.py

this way one can leave a `shscrip.cfg` in this form:

```
${DIR} = ${NAME}_${BAR}/${X}/.

${NAME} ${FOO} ${BAR} ${X_MIN} ${X_MAX} {X_STEP}
mydir1  1  1  10.0 250.0  10
mydir2  2  4  10.0 250.0  10
mydir3  6  12  10.0 250.0  10
```

**Comment by grzanka** [comment]
I was also thinking about something like that. Some basic (not merged) implementation is here:
https://github.com/DataMedSci/pymchelper/pull/185/files

It comes together with multithreading and Fluka support.
