### ISSUE TITLE
Better handling of units

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/pymchelper#357]
This should not be necessary, since they are already written as text strings in the bdo file?

_Originally posted by @nbassler in https://github.com/DataMedSci/pymchelper/pull/348_

**Comment by nbassler** [comment]
Based on the #372 discussion we had, I think the idea is to

- use embedded units, if available
- otherwise fall back to own lists.

This keeps the compability to FLUKA.

So, with #372 this is actually closed?

**Comment by grzanka** [comment]
Yes, should be closed now
