### ISSUE TITLE
add sobp.dat converters for Varian facilities

### ISSUE THREAD

**Issue by nbassler** [DataMedSci/pymchelper#384]
We already have pld2sobp.dat

For varian they may come as dicom or converted to .csv.

How to name these?

**Comment by grzanka** [comment]
As the scope of "input generator scripts" is growing larger and larger (i.e. possibility to include DICOM) I'd rather put them in some separate repository. Then the naming would be much easier to take care of. 
Anyway pld2sobp is already completely independent from rest of the project (is not importing any other piece of the code).

**Comment by nbassler** [comment]
guess it is also a question to define the scope of pymchelper.
Name suggests "Python" "Monte Carlo" "Helpers", and there are also code pieces to generate input files.
One argument is that from a user perspective it is nice not to have to rely on too many separate packages to install.

**Comment by grzanka** [comment]
We can also consider it this way, but then I'd suggest to refactor it heavily, as the main functional groups emerge:
 - output file handling (inspection, conversion to other format)
 - input file handling (like various generator or converters)
I could also imagine another functionality group like:
 - simulation run manager (like parallelizing SH12A or Fluka on multiple processes locally)

**Comment by nbassler** [comment]
it could be unified and made elegant for sure. But for the sake of time, would you allow a simple script first (I have it ready) which first adds the functionality? It can be refactored and made nicer later.
Alternatively I could dump them into the SH12A repo, but that feels wrong as it is useful for FLUKA too.

**Comment by grzanka** [comment]
Sure, you can add it. Just consider adding pydicom as optional dependency (if you need it).
