### ISSUE TITLE
Error while using convertmc on .bdo files

### ISSUE THREAD

**Issue by kkorsgaard** [DataMedSci/pymchelper#393]
Hi 
I experience problems with using convertmc on .bdo files from SHIELD-HIT12A (v0.9.1). The errors is still there for bdo files containing different configurations and for different simulations. It is also present for the different converters for convertmc. Version for pymchelper is  1.5.0. I am using Ubuntu 20.04.2 LTS. I have attached the error message(s) after calling convertmc inspect on bdo file. The files are readable as it is possible to use “frompattern” from pymchelper.input_output to load the files and get the content that way around.
![image](https://user-images.githubusercontent.com/84189339/118281518-953c8980-b4cd-11eb-92bd-76df7ec07907.png)

**Comment by grzanka** [comment]
Hi, can you share more information on how to reproduce the problem ? SHIELD-HIT12A input files would help a lot.

**Comment by kkorsgaard** [comment]
Hi
It is very easy to reproduce as it will happen using convertmc any_converter on any bdo file. Since yesterday I have been testing some more and if I uninstall pymchelper version 1.5.0 and install version 1.4.0 instead it is working perfectly using different converters on different .bdo files and configurations. As I upgrade using “pip install pymchelper –upgrade” it will stop working again and showing the earlier attached message.
I have attached a bdo file from SHIELD-HIT12A (as compressed .zip).
[co_3_dim_0107.zip](https://github.com/DataMedSci/pymchelper/files/6483920/co_3_dim_0107.zip)

**Comment by kkorsgaard** [comment]
Hi again
To be even more precise and to correct my first post – the problem does look to be the reader (both fromfile and frompattern are unable to read the files). I did write in the first post that it is possible to use ‘frompattern’ but this is INCORRECT in pymchelper version 1.5.0 (I had forgotten that I was testing in an environment there I used version 1.4.0)

**Comment by grzanka** [comment]
Hi @kkorsgaard. I confirm the problem, now working on a fix

**Comment by grzanka** [comment]
@kkorsgaard can you test a solution proposed in PR: https://github.com/DataMedSci/pymchelper/pull/396

You can install development version of the package using: 
```
python -m pip install git+https://github.com/DataMedSci/pymchelper.git@fix/393-cannot-read
```

**Comment by kkorsgaard** [comment]
@grzank yes I can and it looks like it is working :-) - I have tested frompattern(), fromfile() and convertmc inspect and image for different files and setups and it is working in all cases :+1:
