### ISSUE TITLE
Check if `_pool._processes` is valid construct

### ISSUE THREAD

**Issue by p1003** [DataMedSci/pymchelper#429]

**Comment by grzanka** [comment]
The `_pool._processes` is not documented, as looking into https://docs.python.org/3/library/multiprocessing.html#multiprocessing.pool.Pool

On the other hand, looking at the source code of python multiprocessing module, it seems that it is being properly set with actual number of processes:
https://github.com/python/cpython/blob/3.9/Lib/multiprocessing/pool.py#L210

```
        if processes is None:
            processes = os.cpu_count() or 1
        if processes < 1:
            raise ValueError("Number of processes must be at least 1")

        if initializer is not None and not callable(initializer):
            raise TypeError('initializer must be a callable')

        self._processes = processes
```

I would therefore leave if as it is and document well the usage of it in the form of the comment in the code
