### ISSUE TITLE
Try if installation of versioneer and pymchelper via --user works

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/pymchelper#47]

**Comment by nbassler** [comment]
pymchelper works. `convertmc` is placed into `~/.local/bin` just as the manual suggested. 

Users may have to add `~/.local/bin` to their `$PATH`

**Comment by nbassler** [comment]
same for versioneer.

**Comment by nbassler** [comment]
@grzanka can be closed?

**Comment by grzanka** [comment]
Yes, I am closing it now.
