### ISSUE TITLE
TRIPCUBE: "Absolute" dose values

### ISSUE THREAD

**Issue by nbassler** [DataMedSci/pymchelper#55]
TRiP dose cubes are in terms of %% dose of PTV.

bdo2txt does not know about PTV, but it would be possible to pass on the information on total # particles and target dose. This should be enough, i.e.:

output = 1000 %% * SHinput [MeV/g/primary] * total_particles [primaries] * 1.602e-10 / targetdose [Gy (user specified, i.e. 2 Gy)]

**Comment by nbassler** [comment]
Realize, that DosCubes are two byte integer arrays. So, they must be scaled up to %% no matter what.
See also issue https://gitlab.au.dk/shieldhit/shieldhit/issues/162

**Comment by nbassler** [comment]
There must also be some handling in the case of no dose was specified. In that case, the dos cube should be normalized to something around 1000, also respecting spikes
Mean value does not work. d = (d / d_max) * 2000.0 might do for now, or smth similar.

**Comment by grzanka** [comment]
@nbassler I've put the code which you sent by email here:
https://github.com/DataMedSci/pymchelper/tree/feature/55-trip-dose
