### ISSUE TITLE
plan.py: issue with coordinate systems

### ISSUE THREAD

**Issue by nbassler** [DataMedSci/pymchelper#609]
assuming beam traveling along z in positive direction is standard in MC.

Unfortunately it seems that y-axis spot data generated by plan has its y-axis flipped. Unsure about x, and possibly z many be negative, assuming system is always righthanded.

This requires some investigation. I suspect there will be no universal solution, but may require an option for plan to convert to either coordinate system which is needed. Beginning to design MC setups traveling in negative z-direction would create much extra confusion and work...

**Comment by grzanka** [comment]
beam along Z direction is a standard for general purpose MC.
If you apply MC to simulation of patient plans I assume this is not a standard anymore. 
When I take look at the PHITS manual for radiotherapy application, the beam source is transformed according to the DICOM plan (see https://phits.jaea.go.jp/rireki-manuale.html).

I can take a look at TOPAS and FLUKA as well.

**Comment by grzanka** [comment]
It seems beam along negative Z is a popular example:

![image](https://user-images.githubusercontent.com/7374733/223420841-76f08744-3cb1-48cb-b2ab-f697d90535a9.png)

**Comment by nbassler** [comment]
imagine the wonderful z-axes pymchelper will produce for DDCs.

**Comment by grzanka** [comment]
What is DDCs ?

wt., 7 mar 2023, 16:25 użytkownik Niels Bassler ***@***.***>
napisał:

**Comment by nbassler** [comment]
depth dose curves

**Comment by nbassler** [comment]
after today's discussion with Leszek, we agreed that I will add -xflip -yflip options to plan.py. This should allow full flexibility.
