### ISSUE TITLE
support for new detector in SHIELD-HIT12A : MCPL

### ISSUE THREAD

**Issue by nbassler** [DataMedSci/pymchelper#628]
pymchelper could collect bdo files from multiple runs and concat and convert to MCPL format.
https://mctools.github.io/mcpl/usage_c/

SH12A development version so far does this:

```c
#define SH_SDET_MCPL           63   /* MC particle list, aka. phase space list */
```
- data are stored in .bdo file in page data array.
- each particle saves 8 data elements: [PDG,x,y,z,vx,vy,vz, e_kin] stored sequentially in a flat array.'
- number of data points in data block:  ndata = nparticles * 8
- number of bytes = ndata * sizeof(double)

postprocess is for now set to `SH_POSTPROC_NONE` but I realize this is not enough, as pymchelper would have to figure out that these are sequential data which should be concatenated from multiple runs.
Would be cleaner to mark this on SH side? maybe defining `SH_POSTPROC_CONCAT` could do this

**Comment by grzanka** [comment]
I believe new postprocessing (or normalisation) flag should be added.
What is the design of the flat array ?
- PDG_1,x_1,y_1,z_1,vx_1,vy_1,vz_1, e_kin_1, PDG_2,x_2,y_2,z_2,vx_2,vy_2,vz_2, e_kin_2, ...
- PDG_1, PDG_2, ..., x_1, x_2, ..., y_1, y_2, ..., z_1, z_2, ..., vx_1, vx_2, ..., vy_1, vy_2, ..., vz_1, vz_2, ..., e_kin_1, e_kin_2, ...

**Comment by grzanka** [comment]
This one may be helpful: https://github.com/mctools/mcpl/issues/70

**Comment by nbassler** [comment]
flat array is currently as you mention in the first bullet point:
`PDG_1,x_1,y_1,z_1,vx_1,vy_1,vz_1, e_kin_1, PDG_2,x_2,y_2,z_2,vx_2,vy_2,vz_2, e_kin_2, ...`
where v is a normalized vector.
I know you prefer the other way, but the first way is nicer during simulation time for memory re-allocation if the number  of particles to be scored is unknown at simulation time.

**Comment by grzanka** [comment]
The plan:
 - [ ] generate BDO files which have phase space output, add them to test/res
 - [ ] introduce new test
 - [ ] fix BDO reader
 - [ ] add new converter endpoint

**Comment by nbassler** [comment]
regarding BDO files for testing, you can use `test/55_plane_phsp` on branch `51-phsp-export` in SH12A repo.
Should work, and files are small.

**Comment by grzanka** [comment]
> regarding BDO files for testing, you can use `test/55_plane_phsp` on branch `51-phsp-export` in SH12A repo.
> Should work, and files are small.

I've already did that:
https://github.com/DataMedSci/pymchelper/pull/648/files#diff-a1e24cfb400a4ff1713372e6269768b58eb852431829fc86031a667e5cf3f55c

Now I am thinking how to adjust "Estimator" pymchelper data structure to accommodate the necessary info
