### ISSUE TITLE
Reading output of Topas simulation

### ISSUE THREAD

**Issue by Bogdan2423** [DataMedSci/pymchelper#646]
https://github.com/yaptide/yaptide/issues/409

**Comment by Bogdan2423** [comment]
@grzanka I think I don't have permission to create branches in this repository

**Comment by grzanka** [comment]
> @grzanka I think I don't have permission to create branches in this repository

I will check

**Comment by grzanka** [comment]
> @grzanka I think I don't have permission to create branches in this repository

I've sent you an invitation for this repository
