### ISSUE TITLE
Empty .txt file generated while using USRTRACK with linear binning

### ISSUE THREAD

**Issue by NatMoj** [DataMedSci/pymchelper#784]
This problem occured while converting fluka .fort file for USRTRACK detector with linear binning. The .txt file which was generated had only headers with NaN values. Please check atteched .fort file and .txt file.
[59.txt](https://github.com/user-attachments/files/18109166/59.txt)
[PASQ_AIR_COL1_E104.7_z=0.00cm0001_fort.zip](https://github.com/user-attachments/files/18109183/PASQ_AIR_COL1_E104.7_z.0.00cm0001_fort.zip)

**Comment by grzanka** [comment]
I am trying to fix the `txt` converter, but in the meantime you can try some other options: `convertmc image PASQ_AIR_COL1_E104.7_z=0.00cm0001_fort.59` or `convertmc plotdata PASQ_AIR_COL1_E104.7_z=0.00cm0001_fort.59`
