### ISSUE TITLE
generatemc -j 5 -p 1000 -s "--time=5:00:00" -w

### ISSUE THREAD

**Issue by NatMoj** [DataMedSci/pymchelper#87]
[prometheus][plgnatada@p0092 plgnatada]$ generatemc -j 5 -p 1000 -s "--time=5:00:00" -w . test_rw3.inp 
usage: generatemc [-h] [-v] [-q] [-V] [-p particle_no] [-j JOBS_NO]
                  [-w WORKSPACE] [-m MC_RUN_TEMPLATE] [-s SCHEDULER_OPTIONS]
                  input
generatemc: error: argument -s/--scheduler_options: expected one argument

**Comment by grzanka** [comment]
Problem is solved in a stupid way by calling:

``generatemc -j 1 -p 100 -w . -s " --time=1:00:00" test_rw3.inp``

note space added

**Comment by grzanka** [comment]
Reported in wrong project, submitted an issue here: https://github.com/DataMedSci/mcpartools/issues/24
