### ISSUE TITLE
Installation instructions for windows users needed

### ISSUE THREAD

**Issue by nbassler** [DataMedSci/pymchelper#88]

**Comment by grzanka** [comment]
some functionalities of pymchelper (tripconverter) depends on pytrip98 package (pytrip core library).
pytrip98 package has C extensions which depends on numpy headers.
Installation of pytrip98 with such C extension (numpy dependent) under Windows is cumbersome. Normally it require compilation and compilation require a lot of prerequisites and doesn't work out of the box. I can think of some smart work-around, but first I would like to know if Windows users could survive without tripconverter functionality. What do you think ?
